### ISSUE TITLE
Pipe robot config to generate function from frontend.

### ISSUE THREAD

**Issue by shueja-personal** [SleipnirGroup/Choreo#73]
Currently, the robot config set in the frontend is not plumbed to the Rust function for generating trajectories.
Create the proper structs in Rust and JS plumbing to accept a robot config in the generate command.

**Comment by jlbabilino** [comment]
The reason I couldn't do this before was because the `generatePath` function was a MobX action of `HolonomicPathStore`, which does not have access to the drivetrain portion of the state model, if I understand it correctly. So it could be changed to be an action of `DocumentModel`, or we could first resolve #64. Moving to DocumentModel might be the right move either way.

**Comment by shueja-personal** [comment]
Closed in #79
